### ISSUE TITLE
Improving Test Coverage, Documentation, and Modular Refactoring

### ISSUE THREAD

**Issue by geoffreynyaga** [amosmachora/react-daraja#46]
## Description

 I'm impressed with the work done so far. As I delve deeper into the codebase, I've identified potential areas for improvement that I believe could significantly enhance the project's maintainability, reliability, and overall developer experience.

## Proposal
Before I create a PR and work on it, I'd like to share areas that I think may improve the coedbase and what the PR will be about.

### Introducing Comprehensive Test Coverage
- Implementing unit tests to ensure the stability and correctness of the existing functionality.
  . e.g. testing daraja constraints like TransactionDesc ,PhoneNumber etc and correct error states are obtained from various inputs.
- Incorporating integration tests to validate the interactions between different modules.
- `NOTE: Even though the testing libraries are dev dependencies, we may have to add required dependancies due to your webpack config and this may increase the package size. Maybe consider Vite in future?`

### Enhancing Documentation:

- Improving the existing documentation to provide clearer insights into the project's structure, functionality, and usage.
- Documenting code internals to assist developers in understanding the underlying logic. Example
``` javascript
cache.put("act", res.data, 3599 * 1000);
  // TODO: Make the one hour cache time dynamic and changed by the user, similar to cacheStaleTime by react query. The default should still be 1 hour
  /* The line `cache.put("act", res.data, 3599 * 1000);` is storing the access token (`res.data`) in a
   cache with the key "act". The cache entry will expire after 3599 seconds (or 59 minutes and 59
   seconds) because the value is multiplied by 1000 to convert it to milliseconds. This caching
   mechanism helps to improve performance by avoiding unnecessary API calls to generate a new access
   token if one is already available in the cache. */
```

### Modular Refactoring for Testability:

- Refactoring certain components to enhance modularity, making the codebase more amenable to testing.

### CI

- Add testing to the Github Actions  so that only PRs with passing tests gets merged and appropriate badges like : `

## Benefits

- Improved reliability through robust test coverage.
- Enhanced developer onboarding with improved documentation.
- A more modular codebase, fostering better maintainability and future extensibility.

## Feedback Requested
Before proceeding, I would appreciate your feedback on this proposal. Your insights are invaluable, and I want to ensure that these proposed changes align with the project's vision and goals.

Feel free to share your thoughts on the proposed approach, suggest any specific areas of focus, or raise any concerns you may have. I am open to collaborating closely with you to implement these improvements effectively.

Looking forward to your input.

**Comment by amosmachora** [comment]
hey @geoffreynyaga great! You have the go-ahead to improve the documentation and tests. 

### Modularity
Modularity part is an issue that this codebase has had for a while. If you could make everything in its module e.g. `react-daraja/react` and `react-daraja/next` then all the base functionalities are imported directly from the library that would be great.

I tried implementing modularity by myself but couldn't manage it that's why I opened the issue.

### Testing
if you could include a GitHub action to test the project on maybe each push to a branch. that would be nice.


If you would also like to include the changes on the documentation website. you can find the repo [here](https://github.com/amosmachora/react-daraja-docs).

Im excited to see your improvement on our codebase!!
